apiVersion: v1
kind: Service
metadata:
  name: model
  namespace: default
  labels:
    app: model
spec:
  type: NodePort
  selector:
    app: model
  ports:
  - name: "8000"
    protocol: TCP
    nodePort: 30100
    port: 8000
    targetPort: 8000
