apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: default
  labels:
    app: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: fastapi
        image: odusseos2024/fastapi:k8s-latest
        ports:
        - containerPort: 8000
      restartPolicy: Always
