apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: default
  labels:
    app: streamlit
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - name: "8501"
    protocol: TCP
    port: 8501
    nodePort: 30000
    targetPort: 8501
