name: MLops CI
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' 
    
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    